# Stricter metrics for readability/reviewability.
cyclomatic_complexity:
  warning: 8
  error: 12

function_body_length:
  warning: 40
  error: 80

type_body_length:
  warning: 200
  error: 300

file_length:
  warning: 300
  error: 800

# Local rules are relaxed during the post-introduction grace period.
# Keep defaults close, but avoid blocking builds due to naming friction.
# TODO: After the ramp-up, remove this relaxation and restore default naming rules.
identifier_name:
  min_length:
    warning: 2
    error: 1
  allowed_symbols: "_"
  validates_start_with_lowercase: false
